name: Checks

on:
  pull_request:

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Authenticate with private NPM package
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > ~/.npmrc

      - name: Lint code
        run: npm run next-lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Build project
        run: npm run next-build
