name: Checks

on:
  pull_request:

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  main:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/overlock-network/anchor:v0.31.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Set default Rust toolchain
        run: rustup default stable

      - name: Generate Solana keypair
        run: solana-keygen new --no-passphrase

      - name: Set Solana target cluster to local
        run: solana config set --url http://localhost:8899

      - name: Anchor Build
        run: anchor build

      - name: Run Anchor tests
        run: anchor test

      - name: Authenticate with private NPM package
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > ~/.npmrc

      - name: Lint code
        run: npm run next-lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Build project
        run: npm run next-build
