name: Deploy Console

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Console

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Console (Next.js static export)
        run: npm run next-build

      - name: Add CNAME file
        run: echo "console.overlock.network" > ./app/out/CNAME

      - name: Deploy Console to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/out
