name: Deploy Programs and Console

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Programs + Console

    container:
      image: ghcr.io/overlock-network/anchor:v0.31.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn 4
        run: corepack prepare yarn@4.4.1 --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set default Rust toolchain
        run: rustup default stable

      - name: Set up deploy keypair
        run: |
          mkdir -p ~/.config/solana
          echo "${{ secrets.DEPLOY_KEYPAIR }}" > ~/.config/solana/id.json

      - name: Set Solana cluster to devnet
        run: solana config set --url https://api.devnet.solana.com

      - name: Anchor Build
        run: anchor build

      - name: Airdrop 5 SOL to deploy key
        run: solana airdrop 5 || echo "Airdrop failed (probably rate-limited), continuing anyway"

      - name: Anchor Deploy
        run: anchor deploy --provider.cluster devnet

      - name: Build Console (Next.js static export)
        run: yarn next-build

      - name: Add CNAME file
        run: echo "console.overlock.network" > ./app/out/CNAME

      - name: Deploy Console to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/out
